# SPDX-License-Identifier: Apache-2.0
version: '2.0'

volumes:
  pgdata:
  walletstore:
services:
  explorerdb.{{ org }}.{{ global_domain }}:
    image: hyperledger/explorer-db:{{ hl_explorer_version }}
    container_name: explorerdb.{{ org }}.{{ global_domain }}
    restart: {{ docker_restart_policy }}
    hostname: explorerdb.{{ org }}.{{ global_domain }}
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  explorer.{{ org }}.{{ global_domain }}:
    image: hyperledger/explorer:latest
    container_name: explorer.{{ org }}.{{ global_domain }}
    hostname: explorer.{{ org }}.{{ global_domain }}
    environment:
      - DATABASE_HOST=explorerdb.{{ org }}.{{ global_domain }}
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - {{ fabric_artifacts }}/crypto-config:/opt/explorer/crypto-config
      - {{ fabric_artifacts }}/explorer-config.json:/opt/explorer/app/platform/fabric/config.json
      - {{ fabric_artifacts }}/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.{{ org }}.{{ global_domain }}:
        condition: service_healthy
